### PR TITLE
Rewrite in TypeScript as a modern ES6 module

### LINKED ISSUE #115: [Problem] spin.js doesn't work with strict CSP
Hello,
We're tightening up our content-security-policy as much as possible. We'd like to use "style-src 'self';" but this breaks spin.js in at least a couple places:
1. Line 30 if arguments[i].nodeName == "STYLE"
2. Line 40 where a new stylesheet is injected into the DOM

For our other code, we've had to migrate all of our inline styles to use css classes instead. Could spin.js be modified to optionally use this behavior and thereby support a strict CSP?

Thanks very much for the great script! I hope we can continue to use it with our high-security site.

### LINKED ISSUE #229: spin.js is not compliant with Chrome Apps
Chrome Apps enforces CSP on all javascript.
I love spin.js and I'm trying to use spin.js in the following project: https://github.com/dart-lang/spark/
Since it's a Chrome Apps, it's not going to be straightforward.

CSP: https://developer.mozilla.org/en-US/docs/Web/Security/CSP

### LINKED ISSUE #325: Bower dependent on jQuery
The docs state...

`No dependencies (jQuery is supported, but not required)`

However, `bower install spin` installs jQuery :(

### LINKED ISSUE #327: Missing Line With Trail Set to 100 in IE
One of the spinner lines isn't visible when the trail is set to 100 in IE. Tested on the latest spin.js version and on the spin.js.org landing page w/ IE11.

screen shot 2016-10-20 at 10 39 16 am

### LINKED ISSUE #340: Spinner is not defined Angular2+
I'am trying use spin.js with typings in my app, but when i try create spinner instance, my componnet throw exception:

`ReferenceError: Spinner is not defined`

Spin.js imported in componnet like this `import "spin.js";`

`"spin.js": "2.3.2",`
`"@types/spin": "2.3.30",`

Code in component:

```
import {Component, AfterViewInit} from "@angular/core";
import "spin.js";

@Component({
    selector: 'loader',
    templateUrl: 'loader.html'
})
export class LoaderComponent implements AfterViewInit{
    ngAfterViewInit(): void {
        this._spinner = new Spinner({color:'#85266c', lines: 12});
    }

    private _spinner: Spinner;
}
```

What i'am doing wrong?

### LINKED ISSUE #341: Rewrite as ES6 module
Hi, I'm one of the core maintainers of [Ladda](https://github.com/hakimel/Ladda/), which relies on spin.js. I'd like to rewrite Ladda as an ES6 module, but this can't be done unless spin.js is also an ES6 module.

Would you be open to a pull request that would change spin.js to an ES6 module? It would have to be released as v3, since this would be a breaking change.

Rewriting spin.js as a native ES6 module should also resolve issue #340.

Other changes that could happen at the same time:

* Remove VML fallback, which is only needed for IE 6, 7, and 8
* Remove minified version of spin.js from repository - most people bundle their modules with Webpack or Rollup, and then minify their whole bundle.
* Remove jquery.spin.js - it seems unnecessary to have two different APIs for using spin.js. Also, I'm not sure how the jQuery version would work well with ES6 modules.

@fgnass @TimothyGu What are your thoughts on this?

### LINKED ISSUE #342: Spinner doesn't animate correctly in Microsoft Edge
Here's a gif showing the default spinner on the spin.js homepage in the latest version of Microsoft Edge (EdgeHTML 16):

edge spinner

Notice that the lines don't animate smoothly in a circle. The animation seems to pause at the upper left line on each iteration. This issue also occurs in previous versions of Microsoft Edge.

### PR DESCRIPTION
**Pull request by theodorejb**
* Replaced dynamic CSS keyframe animations with `requestAnimationFrame`
    * This adds support for Content Security Policy "style-src 'self';" option (resolves #115, resolves #229)
    * Fixes janky animation appearance in Microsoft Edge (resolves #342)
    * Fixes missing line with trail set to 100 in IE (resolves #327)
    * Animation logic is now unified in all browsers
* Library is now distributed as an ES6 module (closes #341, fixes #340)
* Removed useless `hwaccel` option
* Dropped IE 6-8 support and removed VML fallback since it isn't needed for IE 9+
* Moved internal functions out of Spinner instance
* Removed minified files from bundle
* Removed jQuery plugin (closes #325)
* Dropped bower/composer/component/spm support. Install from npm instead (recommended), or save spin.js file in your repo.
* Updated website to use native range inputs rather than polyfill, and remove jQuery usage
* Added CONTRIBUTING.md file

Version 3.0 does not change the public Spinner API, so if you are already using a module bundler such as Webpack or Rollup, upgrading should be as easy as adding the following ES6 module import:

```javascript
import {Spinner} from 'spin.js';
```

### CODE REVIEW

**Comment by theodorejb** [comment]
This should also fix #309.

**Comment by theodorejb** [comment]
You can test the new version here: https://theodorejb.github.io/spin.js/

**Comment by fgnass** [comment]
💯 Thank you very much, your help is highly appreciated! I added you as collaborator to this repo. Feel free to modify whatever you feel is necessary.

**Comment by theodorejb** [comment]
@fgnass Thanks! Can you also add me as a collaborator on npm so I can publish releases? My username is **theodorejb**.

https://www.npmjs.com/package/spin.js/access

**Comment by fgnass** [comment]
Done.

**Pull request merged**
